name: Release Action

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # In order for the GitVersion to properly work you need to clone the repository with the entire history
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: "5.x"

    - name: Install GitVersion
      uses: gittools/actions/gitversion/execute@v1.1.1
      id: gitversion

    - name: Output version to log
      run: echo "Version ${{ steps.gitversion.outputs.semver }}"

    - name: Update ver.txt with new version
      run: echo "${{ steps.gitversion.outputs.semver }}" > ver.txt

    - name: Commit and push ver.txt
      uses: devops-infra/action-commit-push@v0.9.2
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        add_timestamp: true
        commit_prefix: "[AUTO]"
        commit_message: "Automated version update to ${{ steps.gitversion.outputs.semver }}"
        force: false

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.semver }}
        release_name: Release ${{ steps.gitversion.outputs.semver }}
        draft: false
        prerelease: true
